---
borderlessgaming:
    executable: "C:/Program Files (x86)/Borderless Gaming/BorderlessGaming.exe"
    delay: 3000

displayFusion:
    executable: "C:/Program Files (x86)/DisplayFusion/DisplayFusionCommand.exe"
    cloneProfile: "clone"
    extendProfile: "extend"

taskKill: "C:/WINDOWS/system32/taskkill.exe"

mame:
    executable: "C:/Emulators/MAME/mame64.exe"
    workingDir: "C:/Emulators/MAME"
    args:
    screens:
        a: \\.\DISPLAY2
        b: \\.\DISPLAY1
    mameAudioChannelSwitches:
        a: "-audio_right_channel_only"
        b: "-audio_left_channel_only"
    customConfigRoot: "C:/Emulators/mame-configs"

menu:
    keyInputMinDelay: 150
    keyInputMaxDelay: 175
    originMonitorSide: "B"
    realTimeAttractMode: true

bindings:
    player1:
        up: 84 #T
        down: 72 #H
        left: 71 #G
        right: 89 #Y
        a: 78 #N
        b: 66 #B
        start: 219 #[
        coin: 222 #'
    player2:
        up: 85 #U
        down: 75 #K
        left: 74 #J
        right: 73 #I
        a: 188 #,
        b: 77 #M
        start: 221 #]
        coin: 191 #/
    player3:
        up: 81 #Q
        down: 83 #S
        left: 65 #A
        right: 87 #W
        a: 88 #X
        b: 90 #Z
        start: 79 #O
        coin: 190 #.
    player4:
        up: 69 #E
        down: 70 #F
        left: 68 #D
        right: 82 #R
        a: 86 #V
        b: 67 #C
        start: 76 #L
        coin: 186 #;
